var profileSettings=[{id:1,name:"Profile",icon:"user"},{id:2,name:"WorkList",icon:"fas fa-calendar-alt",badge:"5"},{id:3,name:"Password",icon:"fas fa-key"},{id:4,name:"Themes",icon:"fas fa-brush"},{id:5,name:"Logout",icon:"runner"}];var actionSheetItems=[{ID:"01",text:"GEN OTP (TEXT & NUM)  ",type:"normal",icon:"fi fi-sr-rocket",visible:false,onClick:function(){var xxOTPxx=generateLOTP();aMessageAlert('OTP ='+xxOTPxx,'Teal');}},{ID:"02",text:"GEN OTP (NUM ONLY)    ",type:"normal",icon:"fi fi-br-rocket",visible:false,onClick:function(){var xxOTPxx=generateOTP();aMessageAlert('OTP ='+xxOTPxx,'Teal');}},{ID:"04",text:"LOGIN (OTP)           ",type:"normal",icon:"fi fi-sr-lock",visible:true,onClick:function(){aRunLogin(1)}},{ID:"05",text:"LOGIN                 ",type:"normal",icon:"fi fi-br-key",visible:true,onClick:function(){aRunLogin()}},{ID:"03",text:"THEMES                ",type:"normal",visible:true,icon:"fi fi-sr-palette",onClick:function(){aThemeSelect()}}];var aOptionMenu=[{id:"01",icon:"fas fa-cog",text:"",items:[{ID:"101",text:"GEN OTP (TEXT & NUM)  ",type:"normal",icon:"fi fi-sr-rocket",visible:false,onClick:function(){var xxOTPxx=generateLOTP();aMessageAlert('OTP ='+xxOTPxx,'Teal');}},{ID:"102",text:"GEN OTP (NUM ONLY)    ",type:"normal",icon:"fi fi-br-rocket",visible:false,onClick:function(){var xxOTPxx=generateOTP();aMessageAlert('OTP ='+xxOTPxx,'Teal');}},{ID:"103",text:"LOGIN (OTP)           ",type:"normal",icon:"fas fa-lock",visible:false,onClick:function(){aRunLogin(1)}},{ID:"104",text:"New Login             ",type:"normal",icon:"fas fa-key",visible:true,onClick:function(){aRunLogin()}},{ID:"105",text:"Logout                ",type:"danger",icon:"fas fa-sign-out-alt",visible:true,onClick:function(){aaGOTO('index.html')}},{ID:"106",text:"Themes                ",type:"normal",badge:"12",icon:"fas fa-palette",visible:true,onClick:function(){aThemeSelect()}}]}];var contacts=[{name:"Barbara J. Coggins",phone:"512-964-2757",email:"BarbaraJCoggins@rhyta.com",category:"Family"},{name:"Leslie S. Alcantara",phone:"360-684-1334",email:"LeslieSAlcantara@teleworm.us",category:"Friends"},{name:"Chad S. Miles",phone:"520-573-7903",email:"ChadSMiles@rhyta.com",category:"Work"},{name:"Michael A. Blevins",phone:"530-480-1961",email:"MichaelABlevins@armyspy.com",category:"Work"},{name:"Jane K. Hernandez",phone:"404-781-0805",email:"JaneKHernandez@teleworm.us",category:"Friends"},{name:"Kim D. Thomas",phone:"603-583-9043",email:"KimDThomas@teleworm.us",category:"Work"},{name:"Donald L. Jordan",phone:"772-766-2842",email:"DonaldLJordan@dayrep.com",category:"Family"},{name:"Nicole A. Rios",phone:"213-812-8400",email:"NicoleARios@armyspy.com",category:"Friends"},{name:"Barbara M. Roberts",phone:"614-365-7945",email:"BarbaraMRoberts@armyspy.com",category:"Friends"}];function isLocalHost(){let aHostName=window.location.href
if(aHostName.includes("localhost")||aHostName.includes("wikran-w10")){return"http://wikran-w10:8081";}
else{return"https://cbsdev2.locktonwattana.com";};};function generateOTP(){var digits='0123456789';let OTP='';let aG=0;for(let i=0;i<6;i++){aG=Math.floor(Math.random()*10);OTP+=digits[Math.floor(Math.random()*10)];}
return OTP;};function generateLOTP(){var string='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ';let OTP='';var len=string.length;for(let i=0;i<6;i++){OTP+=string[Math.floor(Math.random()*len)];}
return OTP;};function createCookie(name,value,days){if(days){var date=new Date();date.setTime(date.getTime()+(days*24*60*60*1000));var expires="; expires="+date.toGMTString();}
else var expires="";document.cookie=name+"="+value+expires+"; path=/";};function readCookie(name){var nameEQ=name+"=";var ca=document.cookie.split(';');for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)==' ')c=c.substring(1,c.length);if(c.indexOf(nameEQ)==0)return c.substring(nameEQ.length,c.length);}
return null;};function eraseCookie(name){createCookie(name,"",-1);};function setCookie(cname,cvalue,exdays){var d=new Date();d.setTime(d.getTime()+(exdays*24*60*60*1000));var expires="expires="+d.toGMTString();document.cookie=cname+"="+cvalue+";"+expires+";path=/";};function getCookie(cname){var name=cname+"=";var decodedCookie=decodeURIComponent(document.cookie);var ca=decodedCookie.split(';');for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)==' '){c=c.substring(1);}
if(c.indexOf(name)==0){return c.substring(name.length,c.length);}}
return"";};function jqClearAllCookie(){var cookies=$.cookie();for(var cookie in cookies){$.removeCookie(cookie);}}
function aMessageAlert(aaMessage,aaColor){DevExpress.ui.dialog.alert({showTitle:false,messageHtml:"<center style='color:"+aaColor+";'>"+aaMessage+"</center>"});}
function aSendMailDMZ(aRecipient,aRCPeMail,aSendereMail,aCCeMail,aBcceMail,aSubject,aMessage){var myHeaders=new Headers();myHeaders.append("Content-Type","application/json");var raw=JSON.stringify({"toname":aRecipient,"toemail":aRCPeMail,"fromemail":aSendereMail,"ccemail":aCCeMail,"bccemail":aBcceMail,"subject":aSubject,"message":aMessage});var requestOptions={method:'POST',headers:myHeaders,body:raw,redirect:'follow'};fetch("https://cbsdev2.locktonwattana.com/send-email/false",requestOptions).then(response=>response.text()).then(result=>console.log(result)).catch(error=>console.log('error',error));}
function aRolesAction(aRoles,anPos,anChkPos){let aRolesM=["0","ReadOnly","CRU","CRUD","Disable","Import","Export","Import and Export","Printable","Export2PDF","Export2Excel","Report Full Rights"];let aRolesD=["0","000","110","111","0","10","01","11","100","110","101","111"];let aFR=["Data:","Excel:","PDF:","REPORT:"];let aPass=0;let nP=anChkPos-1;let i=anPos-1;let arRoles=aRoles.substring(i,i+1);if(arRoles==="A"){aCC=10;}else if(arRoles==="B"){aCC=11;}else{aCC=Number(arRoles);}
let arRRR=aRolesD[aCC];let arLast=arRRR.substring(nP,nP+1);aPass=Number(arLast);return aPass;}