const aaPositions = [
        { "PositionName": "-" },
        { "PositionName": "Accountant", "PositionLevel": ""  }, 
        { "PositionName": "Administration Officer", "PositionLevel": ""  }, 
        { "PositionName": "Advisor" , "PositionLevel": "" },
        { "PositionName": "Assistant  Division Manager", "PositionLevel": "Assistant Division Manager" },
        { "PositionName": "Assistant Division Manager", "PositionLevel": "Assistant Division Manager" },
        { "PositionName": "Assistant Division Manager & Secretary to Director", "PositionLevel": "Assistant Division Manager" },
        { "PositionName": "Associate Director", "PositionLevel": "Associate Director" },
        { "PositionName": "Business Analyst", "PositionLevel": ""  }, 
        { "PositionName": "Business Development Officer", "PositionLevel": ""  }, 
        { "PositionName": "Car Pool`s Driver", "PositionLevel": "Driver" }, 
        { "PositionName": "Claims Officer" , "PositionLevel": "" }, 
        { "PositionName": "Collection Officer" , "PositionLevel": "" }, 
        { "PositionName": "Collections Officer", "PositionLevel": ""  }, 
        { "PositionName": "Coordinator" , "PositionLevel": "" }, 
        { "PositionName": "Department Manager", "PositionLevel": "Department Manager" },
        { "PositionName": "Director", "PositionLevel": "Director" },
        { "PositionName": "Director – Business Development", "PositionLevel": "Director" },
        { "PositionName": "Division Manager", "PositionLevel": "Division Manager" }, 
        { "PositionName": "Division Manager - Finance", "PositionLevel": "Division Manager" },
        { "PositionName": "Division Manager–Web Developer/Analyst", "PositionLevel": "Division Manager" }, 
        { "PositionName": "Driver", "PositionLevel": "Driver" }, 
        { "PositionName": "Executive Chairman", "PositionLevel": "Executive Chairman" }, 
        { "PositionName": "Finance Officer", "PositionLevel": ""  }, 
        { "PositionName": "Khun Julio`s Driver", "PositionLevel": "Driver" },
        { "PositionName": "Khun Suradee`s Driver", "PositionLevel": "Driver" }, 
        { "PositionName": "Maid", "PositionLevel": "Maid" },
        { "PositionName": "Management Trainee" }, { "PositionName": "Operations Officer" },
        { "PositionName": "Personal Assistant to CEO", "PositionLevel": ""  }, 
        { "PositionName": "Programmer", "PositionLevel": ""  }, 
        { "PositionName": "Risk Engineer", "PositionLevel": ""  }, 
        { "PositionName": "Senior Department Manager", "PositionLevel": "Senior Department Manager" }, 
        { "PositionName": "Senior Director", "PositionLevel": "Senior Director" }, 
        { "PositionName": "Senior Division Manager", "PositionLevel": "Senior Division Manager" },
        { "PositionName": "Senior Division Manager - Accounting", "PositionLevel": "Senior Division Manager" },
        { "PositionName": "Senior Division Manager - Finance", "PositionLevel": "Senior Division Manager" }, 
        { "PositionName": "Senior Finance Officer", "PositionLevel": "" }, 
        { "PositionName": "System Coordinator", "PositionLevel": ""  }
    ];