const aRightsAccess = [
    {
        "FullRightsName": "admin",
        "AccessRights": "admin",
        "DataAccess": "",
        "ExcelRights": "",
        "PDFRights": "",
        "ReportRights": "",
    }, 
    {
        "FullRightsName": "hrSupervisor",
        "AccessRights": "hrSupervisor",
        "DataAccess": "",
        "ExcelRights": "",
        "PDFRights": "",
        "ReportRights": "",
    },
    {
        "FullRightsName": "hrStaff",
        "AccessRights": "hrStaff",
        "DataAccess": "",
        "ExcelRights": "",
        "PDFRights": "",
        "ReportRights": "",
    },    
    {
        "FullRightsName": "faSupervisor",
        "AccessRights": "faSupervisor",
        "DataAccess": "",
        "ExcelRights": "",
        "PDFRights": "",
        "ReportRights": "",
    },
    {
        "FullRightsName": "faStaff",
        "AccessRights": "faStaff",
        "DataAccess": "",
        "ExcelRights": "",
        "PDFRights": "",
        "ReportRights": "",
    },    
    {
        "FullRightsName": "HODApp",
        "AccessRights": "HODApp",
        "DataAccess": "",
        "ExcelRights": "",
        "PDFRights": "",
        "ReportRights": "",
    },
    {
        "FullRightsName": "nuserf",
        "AccessRights": "nuserf",
        "DataAccess": "",
        "ExcelRights": "",
        "PDFRights": "",
        "ReportRights": "",
    },
    {
        "FullRightsName": "nuserm",
        "AccessRights": "nuserm",
        "DataAccess": "",
        "ExcelRights": "",
        "PDFRights": "",
        "ReportRights": "",
    },
    {
        "FullRightsName": "nusert",
        "AccessRights": "nusert",
        "DataAccess": "",
        "ExcelRights": "",
        "PDFRights": "",
        "ReportRights": "",
    },   
    {
        "FullRightsName": "usero",
        "AccessRights": "nusero",
        "DataAccess": "",
        "ExcelRights": "",
        "PDFRights": "",
        "ReportRights": "",
    },      
           
]

